services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # Path to Dockerfile in /docker folder
    container_name: laravel-app
    volumes:
      - ./:/var/www/html                 # Mount project root directory
      - ./docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
     # - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini  # Mount xdebug.ini file
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY
    ports:
      - "9000:9000"   # PHP-FPM
      - "9003:9003"   # Xdebug
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel-webserver
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf  # Path to Nginx config
      - ./:/var/www/html
    ports:
      - "888:80"
    networks:
      - laravel

  laravel-db:
    image: postgres:13
    container_name: laravel-db
    ports:
        - "5432:5432"
    environment:
        POSTGRES_DB: marketplace
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: marketplace
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
