version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: laravel-app
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
    ports:
      - "9000:9000"   # PHP-FPM
      - "9003:9003"   # Xdebug
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel-webserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../:/var/www/html
    ports:
      - "80:80"
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: laravel-db
    env_file:
      - ./postgres.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
